name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    name: Run on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load .env
        uses: Steph0/dotenv-configserver@v1
        with:
          repository: 'flagarde/dotenv'
      - name: Print .env
        run : |
          env
