name: Ubuntu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ubuntu:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load .env
        uses: Steph0/dotenv-configserver@v1
        with:
          repository: 'flagarde/dotenv'
      - name: Print .env
        run : env
